// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.ContractManagementAPI.DataAccess;

namespace Pitstop.ContractManagementAPI.Migrations
{
    [DbContext(typeof(ContractManagementDBContext))]
    [Migration("20190205191709_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.ContractManagementAPI.Model.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dias");

                    b.Property<string>("Grupo");

                    b.Property<string>("Nombre");

                    b.Property<string>("Poliza");

                    b.Property<decimal>("Precio");

                    b.HasKey("RateId");

                    b.ToTable("Rate");
                });
#pragma warning restore 612, 618
        }
    }
}
