// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.ContractManagementAPI.DataAccess;

namespace Pitstop.ContractManagementAPI.Migrations
{
    [DbContext(typeof(ContractManagementDBContext))]
    partial class ContractManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {

            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pitstop.ContractManagementAPI.Model.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dias");

                    b.Property<string>("Grupo");

                    b.Property<string>("Nombre");

                    b.Property<string>("Poliza");

                    b.Property<decimal>("Precio");

                    b.HasKey("RateId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Pitstop.ContractManagementAPI.Model.Contract", b =>
            {
                b.Property<int>("ContractId")
                    .ValueGeneratedOnAdd();

                b.Property<int>("CustomerId");

                b.Property<int>("VehicleId");

                b.Property<int>("RateId");

                b.HasKey("ContractId");

                b.ToTable("Contract");
            });

            modelBuilder.Entity("Pitstop.ContractManagementAPI.Model.VAT", b =>
            {
                b.Property<int>("VatId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Nombre");

                b.Property<int>("Tipo");

                b.Property<bool>("Current");

                b.HasKey("VatId");

                b.ToTable("VAT");
            });

        }
    }
}
